// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9CNmW3HOZXTWDWK6mLYqwy-yWEzIB1lE',
    appId: '1:867104063608:web:878bc82421832004abad8d',
    messagingSenderId: '867104063608',
    projectId: 'jungle-jumper-7a8d3',
    authDomain: 'jungle-jumper-7a8d3.firebaseapp.com',
    storageBucket: 'jungle-jumper-7a8d3.appspot.com',
    measurementId: 'G-3EZ8M5PX3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uWEIJX7unzGradQxUKz4KlpTxcjDfZo',
    appId: '1:867104063608:android:70c189afd10cf9b5abad8d',
    messagingSenderId: '867104063608',
    projectId: 'jungle-jumper-7a8d3',
    storageBucket: 'jungle-jumper-7a8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRbogNXUb95LP1WYVyWFIy3T1mW-Obdf0',
    appId: '1:867104063608:ios:bf0d28a1c93f2db9abad8d',
    messagingSenderId: '867104063608',
    projectId: 'jungle-jumper-7a8d3',
    storageBucket: 'jungle-jumper-7a8d3.appspot.com',
    iosBundleId: 'com.leveltwenty.final_firebase_test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRbogNXUb95LP1WYVyWFIy3T1mW-Obdf0',
    appId: '1:867104063608:ios:bf0d28a1c93f2db9abad8d',
    messagingSenderId: '867104063608',
    projectId: 'jungle-jumper-7a8d3',
    storageBucket: 'jungle-jumper-7a8d3.appspot.com',
    iosBundleId: 'com.leveltwenty.final_firebase_test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9CNmW3HOZXTWDWK6mLYqwy-yWEzIB1lE',
    appId: '1:867104063608:web:9af7073c4661c7dbabad8d',
    messagingSenderId: '867104063608',
    projectId: 'jungle-jumper-7a8d3',
    authDomain: 'jungle-jumper-7a8d3.firebaseapp.com',
    storageBucket: 'jungle-jumper-7a8d3.appspot.com',
    measurementId: 'G-DKBZHL9EM7',
  );
}
